<?php

namespace Votenmasse\VotenmasseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DonnerAvisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonnerAvisRepository extends EntityRepository
{
}
