<?php

namespace Votenmasse\VotenmasseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GroupeUtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeUtilisateurRepository extends EntityRepository
{
}
