votenmasse_votenmasse_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: VotenmasseVotenmasseBundle:Default:index }

votenmasse_votenmasse_index:
    pattern: /
    defaults : { _controller: VotenmasseVotenmasseBundle:Votenmasse:index }

votenmasse_votenmasse_accueil:
    pattern: /accueil
    defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:index }

votenmasse_votenmasse_connexion:
    pattern: /connexion
    defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:connexion }

votenmasse_votenmasse_deconnexion:
   pattern: /deconnexion
   defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:deconnexion }

votenmasse_votenmasse_creation_vote:
    pattern: /creation/vote
    defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:creationVote }

votenmasse_votenmasse_votes:
    pattern: /liste/votes
    defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:votes }

votenmasse_votenmasse_resultats:
    pattern: /resultats
    defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:resultats }

votenmasse_votenmasse_vote:
    pattern: /vote/{vote}
    defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:afficherVote, vote: null }

votenmasse_votenmasse_creation_groupe:
    pattern: /creation/groupe
    defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:creationGroupe }

votenmasse_votenmasse_administration:
   pattern: /administration
   defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:administration }

votenmasse_votenmasse_forum:
   pattern: /forum/liste/votes
   defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:forum }

votenmasse_votenmasse_commentaire:
   pattern: /commentaire/{vote}/{supp}
   defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:commentaire, vote: null, supp: false }

votenmasse_votenmasse_groupes:
   pattern: /liste/groupes
   defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:groupes }

votenmasse_votenmasse_affichage_groupe:
    pattern: /groupe/{groupe_id}
    defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:afficherGroupe, groupe_id: null }

votenmasse_votenmasse_rejoindre_groupe:
    pattern: /groupe/rejoindre/{groupe_id}
    defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:rejoindreGroupe, groupe_id: null }

votenmasse_votenmasse_quitter_groupe:
    pattern: /groupe/quitter/{groupe_id}
    defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:quitterGroupe, groupe_id: null }

votenmasse_votenmasse_supprimer_groupe:
    pattern: /groupe/supprimer/{groupe_id}
    defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:supprimerGroupe, groupe_id: null }

votenmasse_votenmasse_supprimer_utilisateur:
    pattern: /utilisateur/supprimer
    defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:supprimerUtilisateur }

votenmasse_votenmasse_groupe_accepter_utilisateur:
    pattern: /groupe/accepter/utilisateur
    defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:groupeAjouterUtilisateur }

votenmasse_votenmasse_groupe_refuser_utilisateur:
    pattern: /groupe/refuser/utilisateur
    defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:groupeRefuserUtilisateur }

votenmasse_votenmasse_vote_supprimer:
    pattern: /vote/action/supprimer
    defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:supprimerVote }

votenmasse_votenmasse_groupe_supprimer_utilisateur:
   pattern: /groupe/action/supprimer/utilisateur
   defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:groupeSupprimerUtilisateur }

votenmasse_votenmasse_groupe_donner_privilege:
   pattern: /groupe/action/donner/privilege
   defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:groupeDonnerPrivilege }

votenmasse_votenmasse_groupe_supprimer_privilege:
   pattern: /groupe/action/supprimer/privilege
   defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:groupeSupprimerPrivilege }

votenmasse_votenmasse_vote_moderer:
   pattern: /vote/moderer/{vote_id}
   defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:voteModerer, vote_id: null }

votenmasse_votenmasse_supprimer_vote:
   pattern: /vote/supprimer/action
   defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:voteSupprimer }

votenmasse_votenmasse_vote_ajouter_moderateur:
   pattern: /vote/ajouter/moderateur
   defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:voteAjouterModerateur }

votenmasse_votenmasse_vote_supprimer_moderateur:
   pattern: /vote/supprimer/moderateur
   defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:voteSupprimerModerateur }

votenmasse_votenmasse_vote_supprimer_commentaire:
   pattern: /vote/supprimer/commentaire
   defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:commentaireSupprimer }

votenmasse_votenmasse_moderation_supprimer_utilisateur:
    pattern: /moderation/supprimer/utilisateur/{log}
    defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:moderationSupprimer, log: null}

votenmasse_votenmasse_moderation_accepter_utilisateur:
    pattern: /moderation/accepter/utilisateur/{log}
    defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:moderationAccepter, log: null}

votenmasse_votenmasse_moderation:
    pattern: /moderation/{etat}
    defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:moderation, etat: null }

votenmasse_votenmasse_bannir:
    pattern: /bannir
    defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:bannir }

votenmasse_votenmasse_g_supprimer:
   pattern: /g/supprimer
   defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:gSupprimer }

votenmasse_votenmasse_v_supprimer:
   pattern: /v/supprimer
   defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:vSupprimer }

votenmasse_votenmasse_c_supprimer:
   pattern: /c/supprimer
   defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:cSupprimer }

votenmasse_votenmasse_aide:
  pattern: /aide
  defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:aide }

votenmasse_votenmasse_a_propos:
  pattern: /a_propos
  defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:aPropos }

votenmasse_votenmasse_developpeurs:
  pattern: /developpeurs
  defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:developpeurs }