votenmasse_votenmasse_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: VotenmasseVotenmasseBundle:Default:index }

votenmasse_votenmasse_index:
    pattern: /
    defaults : { _controller: VotenmasseVotenmasseBundle:Votenmasse:index }

votenmasse_votenmasse_accueil:
    pattern: /accueil
    defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:index }

votenmasse_votenmasse_connexion:
    pattern: /connexion
    defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:connexion }

votenmasse_votenmasse_deconnexion:
   pattern: /deconnexion
   defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:deconnexion }

votenmasse_votenmasse_creation_vote:
    pattern: /creation/vote
    defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:creationVote }

votenmasse_votenmasse_votes:
    pattern: /liste/votes
    defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:votes }

votenmasse_votenmasse_resultats:
    pattern: /resultats
    defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:resultats }

votenmasse_votenmasse_vote:
    pattern: /vote/{vote}
    defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:afficherVote, vote: null }

votenmasse_votenmasse_creation_groupe:
    pattern: /creation/groupe
    defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:creationGroupe }

votenmasse_votenmasse_administration:
   pattern: /administration
   defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:administration }

votenmasse_votenmasse_forum:
   pattern: /forum/liste/votes
   defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:forum }

votenmasse_votenmasse_commentaire:
   pattern: /commentaire/{vote}/{supp}
   defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:commentaire, vote: null, supp: null }

votenmasse_votenmasse_groupes:
   pattern: /liste/groupes
   defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:groupes }

votenmasse_votenmasse_affichage_groupe:
    pattern: /groupe/{groupe_id}
    defaults: { _controller: VotenmasseVotenmasseBundle:Votenmasse:afficherGroupe, groupe_id: null }