parameters:
#    votenmasse_votenmasse.example.class: Votenmasse\VotenmasseBundle\Example

services:
#    votenmasse_votenmasse.example:
#        class: %votenmasse_votenmasse.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
